quadruped:
  # Publish all joint states
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 10000

  # controllers
  joint_trajectory_controller:
    type: effort_controllers/JointTrajectoryController

    joints:
      - front_right_leg3_joint
      - front_right_leg2_joint
      - front_right_leg1_joint
      - back_right_leg3_joint
      - back_right_leg2_joint
      - back_right_leg1_joint
      - front_left_leg3_joint
      - front_left_leg2_joint
      - front_left_leg1_joint
      - back_left_leg3_joint
      - back_left_leg2_joint
      - back_left_leg1_joint

    gains:
      front_right_leg1_joint: {p: 500, d: 50}
      front_right_leg2_joint: {p: 500, d: 50}
      front_right_leg3_joint: {p: 500, d: 50}
      front_left_leg1_joint: {p: 500, d: 50}
      front_left_leg2_joint: {p: 500, d: 50}
      front_left_leg3_joint: {p: 500, d: 50}
      back_right_leg1_joint: {p: 500, d: 50}
      back_right_leg2_joint: {p: 500, d: 50}
      back_right_leg3_joint: {p: 500, d: 50}
      back_left_leg1_joint: {p: 500, d: 50}
      back_left_leg2_joint: {p: 500, d: 50}
      back_left_leg3_joint: {p: 500, d: 50}
