quadruped:
  # Publish all joint states
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 600

  # controllers
  joint_trajectory_controller:
    type: "position_controllers/JointTrajectoryController"

    joints:
      - front_right_leg3_joint
      - front_right_leg2_joint
      - front_right_leg1_joint
      - back_right_leg3_joint
      - back_right_leg2_joint
      - back_right_leg1_joint
      - front_left_leg3_joint
      - front_left_leg2_joint
      - front_left_leg1_joint
      - back_left_leg3_joint
      - back_left_leg2_joint
      - back_left_leg1_joint

    gains:
      front_right_leg1_joint: {p: 0, d: 0.00, i: 0, i_clamp: 0}
      front_right_leg2_joint: {p: 0, d: 0.00, i: 0, i_clamp: 0}
      front_right_leg3_joint: {p: 0, d: 0.00, i: 0, i_clamp: 0}
      front_left_leg1_joint: {p: 0, d: 0.00, i: 0, i_clamp: 0}
      front_left_leg2_joint: {p: 0, d: 0.00, i: 0, i_clamp: 0}
      front_left_leg3_joint: {p: 0, d: 0.00, i: 0, i_clamp: 0}
      back_right_leg1_joint: {p: 0, d: 0.00, i: 0, i_clamp: 0}
      back_right_leg2_joint: {p: 0, d: 0.00, i: 0, i_clamp: 0}
      back_right_leg3_joint: {p: 0, d: 0.00, i: 0, i_clamp: 0}
      back_left_leg1_joint: {p: 0, d: 0.00, i: 0, i_clamp: 0}
      back_left_leg2_joint: {p: 0, d: 0.00, i: 0, i_clamp: 0}
      back_left_leg3_joint: {p: 0, d: 0.00, i: 0, i_clamp: 0}

    constraints:
      goal_time: 10020.0
      stopped_velocity_tolerance: = 20100
      front_right_leg1_joint: {trajectory: 0.2, goal: 1000.6}
      front_right_leg2_joint: {trajectory: 0.2, goal: 1000.6}
      front_right_leg3_joint: {trajectory: 0.2, goal: 1000.6}
      front_left_leg1_joint: {trajectory: 0.2, goal: 1000.6}
      front_left_leg2_joint: {trajectory: 0.2, goal: 1000.6}
      front_left_leg3_joint: {trajectory: 0.2, goal: 1000.6}
      back_right_leg1_joint: {trajectory: 0.2, goal: 1000.6}
      back_right_leg2_joint: {trajectory: 0.2, goal: 1000.6}
      back_right_leg3_joint: {trajectory: 0.2, goal: 1000.6}
      back_left_leg1_joint: {trajectory: 0.2, goal: 1000.6}
      back_left_leg2_joint: {trajectory: 0.2, goal: 1000.6}
      back_left_leg3_joint: {trajectory: 0.2, goal: 1000.6}

    stop_trajectory_duration: 0.5
    state_publish_rate:  25
    action_monitor_rate: 10
