<?xml version="1.0"?>
<robot name="box" xmlns:xacro="http://ros.org/wiki/xacro">
  <!-- Gazebo plugin for ROS Control -->
  <gazebo>
    <plugin name="gazebo_ros_control" filename="libgazebo_ros_control.so">
      <robotNamespace>/quadruped</robotNamespace>
    </plugin>
  </gazebo>

  <xacro:property name="scaling_factor" value="1" />
  <!--height:z width:y width:x -->
  <xacro:property name="box_width" value="${0.15}" />
  <xacro:property name="box_height" value="${0.45}" />
  <xacro:property name="box_length" value="${1.5}" />
  <xacro:property name="box_mass" value="${1000}" />


  <!-- Inertia -->
  <xacro:macro name="box_inertial" params="mass width depth">
    <inertial>
      <mass value="${mass}" />
      <inertia ixx="${mass*(width*width+depth*depth)/12.0}" ixy="0.0" ixz="0.0" iyy="${mass*(width*width+depth*depth)/12.0}" iyz="0.0" izz="${mass*(width*width+depth*depth)/12.0}" />
    </inertial>
  </xacro:macro>

  <xacro:macro name="sphere_inertial" params="mass radius">
    <inertial>
      <mass value="${mass}" />
      <inertia ixx="0.1" ixy="0.0" ixz="0.0" iyy="0.1" iyz="0.0" izz="0.1"/>
    </inertial>
  </xacro:macro>

  <link name="dummy_link">
    <visual>
      <geometry>
        <box size="0.01 0.01 0.01"/>
      </geometry>
      <material name="black"/>
    </visual>
    <inertial>
      <mass value="0.01" />
      <inertia ixx="0.00001" ixy="0.0" ixz="0.0" iyy="0.00001" iyz="0.0" izz="0.00001" />
    </inertial>
    <gazebo reference="dummy_link">
    </gazebo>
  </link>


  <link name="base_link">
    <visual>
      <geometry>
        <box size="${box_width} ${box_length} ${box_height}"/>
      </geometry>
      <material name="red"/>
    </visual>
    <collision>
      <geometry>
        <box size="${box_width} ${box_length} ${box_height}"/>
      </geometry>
    </collision>
    <xacro:box_inertial mass="${box_mass}" width="${box_length}" depth="${box_length}"/>
  </link>
  <joint name="dummy_base_joint" type="fixed">
    <parent link="dummy_link"/>
    <child link="base_link"/>
    <origin xyz="0 0 ${0.5*box_height}" rpy="0 0 0"/>
  </joint>
  <gazebo reference="base_link">
    <mu1>100000.0</mu1>
    <mu2>100000.0</mu2>
    <material>Gazebo/Red</material>
  </gazebo>
  <gazebo reference="dummy_base_joint">
    <provideFeedback>true</provideFeedback>
    <disableFixedJointLumping>true</disableFixedJointLumping>
    <material>Gazebo/Red</material>
  </gazebo>

</robot>
